services:
  - type: web
    name: home-repair-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: true
      - key: SECRET_KEY
        value: your-secret-key-12345
    plan: free
